version: "3"

services:
  api:
    image: node:latest
    working_dir: /app
    command: npm start
    ports:
      - "5006:3000"
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=testRoot
      - TYPEORM_PASSWORD=root
      - TYPEORM_DATABASE=dev_test
      - TYPEORM_PORT=3306
      - TYPEORM_ENTITIES=src/entity/**/*.ts
      - TYPEORM_MIGRATIONS=src/migration/**/*.ts
      - TYPEORM_MIGRATIONS_RUN=src/migration
      - TYPEORM_MIGRATIONS_DIR=src/migration
    volumes:
      - ./:/app

  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev_test
      - MYSQL_USER=testRoot
      - MYSQL_PASSWORD=root
